micronaut:
  application:
    name: petClinicConcierge
  server:
    port: 32584
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: false
  prometheus:
    enabled: false
consul:
  client:
    defaultZone: 'consul:8500'
    registration:
      enabled: true
tracing:
  zipkin:
    http:
      url: http://host.docker.internal:9411
    enabled: true
    sampler:
      probability: 1